version: '3'

services:
  # frontend:
  #   build: frontend
  #   ports:
  #     - 8501:8501
  #   depends_on:
  #     - backend
  #   volumes:
  #       - ./storage:/storage
  backend:
    build: backend
    ports:
      - 8501:8501
    volumes:
      - ./storage:/storage


networks:
  webnet:
    driver: bridge